### ISSUE TITLE
Using Thread/Async properly for parsing to speed up

### ISSUE THREAD

**Issue by TheRustyPickle** [vlad-onis/twir_parser#28]
I noticed that most of the time is spent parsing the data on `parse_page` during online searches. Using threads or async more effectively can drastically improve performance and reduce parsing time.

**Comment by vlad-onis** [comment]
That is 200% on my to-do list. I was thinking to do some measurements to see how much time is spent where. Right now the online search is extremely slow and that will have to change. I'll add an issue to have a branch where we can see some performance metrics

**Comment by vlad-onis** [comment]
Another little optimisation: Parse page itself is slow because it is parsing every link on the page and it is checking it with lychee. But I think even the vector of issues that we build should not contain all random links that can be found on a page (like the reddit link for who's hiring, or compiler updates). I feel like most people will use this tool to search for articles that explain a certain concept, so we can do a lot of pruning to make things more efficient.

**Comment by vlad-onis** [comment]
Hello @TheRustyPickle.  We've just got a contribution that tackles this exact issue. Thought I'd let you know as well, let me know if that's good enough and I'll close this issue, Otherwise I'd love to head your opinion.

**Comment by TheRustyPickle** [comment]
Just tried the latest version. Performance has improved a lot🚀! Let's close the issue.
